name: Deploy Node App

on:
  push:
      branches:
          - mern-ec2-docker
jobs: 
    build:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout Source
              uses: action/checkout@v4
            - name: Login to docker hub
              run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}} 
            - name: Build Docker Image
              run: docker build -t bayrambayraktar/node-product-user-service .
            - name: Publish Image to docker hub 
              run: docker push bayrambayraktar/node-product-user-service:latest
        
    deploy:
        needs: build
        runs-on: self-hosted
        steps:
          - name: pull image From docker hub
            run: docker pull bayrambayraktar/node-product-user-service:latest
          - name: Run Docker Container
            run: docker run -d -p 4000:4000 --name nodejs-app-container -e MONGO_PASSWORD='${{secrets.MONGO_PASSWORD}}' bayrambayraktar/node-product-user-service

